remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Apoorv Singh
description: Tech Lead | Sr. Machine Learning Engineer | Self-driving cars | Robotics | Carnegie Mellon
